import { describe, expect, it } from "vitest";
import { requestedEffectIntent } from "../src/core/task-verification/requested-effect-intent.ts";

describe("requestedEffectIntent", () => {
  it.each([
    "What does the current implementation do?",
    "Read BRIEF.md and answer with the two requested bullets.",
    "Compare the current and previous behavior.",
    "Translate this explanation into Ukrainian.",
    "Объясни, как работает текущая реализация.",
    "Show me the current status.",
    "Give me a summary.",
    "List the remaining issues.",
    "Describe how this works.",
    "Report the latest benchmark results.",
    "Check whether indexing works.",
    "Calculate 2+2.",
    "Write a two-bullet decision note in your response.",
    "Write a two-bullet decision note in your response only.",
    "Write the answer in your response, please.",
    "Compose the answer in chat, please.",
    "What happens after you delete a file?",
    "Explain what happens before you publish a package.",
    "Tell me what changes after you update the configuration.",
    "Tell me what happens after sending an approval message.",
    "Tell me what happens once you finish sending the approval message.",
    "Tell me what happens once you have successfully sent the approval message.",
    "Compare behavior before and after migration.",
    "List the tasks before release.",
    "Report benchmark results after the run.",
    "Compare rates before and after spring.",
    "Report events after Thanksgiving.",
    "Compare behavior before and after the update.",
    "Report the current status after the deployment.",
    "List changes following the update.",
    "Compare sales before the new building opened.",
    "Report events after the setting sun.",
    "Could you explain what happens after creating GUIDE.md?",
    "What happens after deletion?",
  ])("recognizes response-only work independently of the completion checklist: %s", (prompt) => {
    expect(requestedEffectIntent([prompt])).toBe("response_only");
  });

  it.each([
    "Create GUIDE.md with the requested explanation.",
    "Implement the requested runtime behavior.",
    "Send the requested approval message.",
    "Read BRIEF.md, then update GUIDE.md.",
    "Explain the current behavior, but create GUIDE.md.",
    "Please explain this but send the approval message.",
    "What I need you to do is implement the requested behavior.",
    "Write a two-bullet note in your response and send the approval message.",
    "What I need is for you to send the approval message.",
    "What you should do is create GUIDE.md.",
    "What I want you to do is implement the requested behavior.",
    "Write the answer in your response.json file.",
  ])("requires an effect when the user requests one: %s", (prompt) => {
    expect(requestedEffectIntent([prompt])).toBe("effect_required");
  });

  it.each([
    "¿Puedes explicar cómo funciona?",
    "この仕組みを説明してください。",
    "Crea GUIDE.md con la explicación solicitada.",
    "Envía el mensaje de aprobación solicitado.",
    "GUIDE.mdを作成してください。",
    "承認メッセージを送信してください。",
    "Створи GUIDE.md із поясненням.",
    "Надішли повідомлення про схвалення.",
    "Write a two-bullet note in your response after sending the approval message.",
    "Write a two-bullet note in your response once you have sent the approval message.",
    "Write the answer in your response after the approval message is sent.",
    "Write the answer in your response: after sending the approval message.",
    "Write the answer in your response, after sending the approval message.",
    "Write the answer in your response; once you have sent the approval message.",
    "Write the answer in your response — after the approval message is sent.",
    "Write the answer in your response. After sending the approval message.",
    "Write the answer in your response, but first send the approval message.",
    "Read BRIEF.md, then write the answer in your response after sending the approval message.",
    "Explain the behavior, then write the answer in your response after sending the approval message.",
    "Answer in your response after sending the approval message.",
    "Give me the answer in your response after sending the approval message.",
    "Report the result in your response after sending the approval message.",
    "Answer after sending the approval message.",
    "Tell me once you have sent the approval message.",
    "Report back after creating GUIDE.md.",
    "Give me two bullets, but first create GUIDE.md.",
    "Show me the result after you update the configuration.",
    "Answer, but first send the approval message.",
    "Tell me what happens, but first create GUIDE.md.",
    "Explain how it works, but first send the approval message.",
    "Show me when it runs, but first update the configuration.",
    "Tell me as soon as you have sent the approval message.",
    "Give me two bullets following creation of GUIDE.md.",
    "Tell me once you've sent the approval message.",
    "Tell me once you’ve sent the approval message.",
    "Tell me as soon as you've sent the approval message.",
    "Show me the result when you're done updating the configuration.",
    "Report back after the approval message is sent.",
    "What happens, but first create GUIDE.md.",
    "How does it work, but first send the approval message.",
    "What happens? First create GUIDE.md.",
    "What happens: first create GUIDE.md.",
    "How does it work; first send the approval message.",
    "What happens? Please first create GUIDE.md.",
    "What happens? First please create GUIDE.md.",
    "What happens, and first create GUIDE.md.",
    "What happens — first create GUIDE.md.",
    "What happens – first create GUIDE.md.",
    "What happens?\n- First create GUIDE.md.",
    "Tell me once you finish sending the approval message.",
    "Report back after you complete creating GUIDE.md.",
    "Show me the result when you’re finished updating the configuration.",
    "Report back after the approval message has been successfully sent.",
    "Tell me once you have successfully sent the approval message.",
    "Tell me once you’ve successfully sent the approval message.",
    "Report back after you successfully create GUIDE.md.",
    "Show me the result when you actually update the configuration.",
    "Tell me after successfully sending the approval message.",
    "Report back once you are completely done updating the configuration.",
  ])("requires an independent declaration for unclassified language: %s", (prompt) => {
    expect(requestedEffectIntent([prompt])).toBe("unknown");
  });

  it.each([
    [["Explain the current behavior clearly.", "Crea GUIDE.md con la explicación solicitada."], "unknown"],
    [["Give me a summary.", "承認メッセージを送信してください。"], "unknown"],
    [["Give me a summary.", "Implement the requested behavior."], "effect_required"],
  ] as const)("does not let an earlier response mask a later prompt: %j", (prompts, expected) => {
    expect(requestedEffectIntent(prompts)).toBe(expected);
  });
});
