export const PROJECT_INSTRUCTIONS_PROMPT_BUDGET = 4_996;
export const PROJECT_INSTRUCTIONS_PROMPT_TARGET = 2_000;
export const PROJECT_INSTRUCTION_COMPILER_BODY_MAX_CHARS = 3_500;
export const PROJECT_INSTRUCTION_MODULE_MAX_BYTES = 24_000;
export const PROJECT_INSTRUCTION_CATALOG_PAGE_MAX_BYTES = 128_000;
export const PROJECT_INSTRUCTION_READ_MAX_BYTES = 512_000;
export const PROJECT_INSTRUCTION_RULE_EXPANSION_MAX_MODULES = 16;
